repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --preserve-quotes, --offset, '2']
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.58.0
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: golines
        name: golines
        description: A golang formatter that fixes long lines.
        entry: golines . -w --ignore-generated
        types: [go]
        language: golang
        pass_filenames: false
