#!/bin/bash

set -ex

DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}"

goose -dir /app/migrations postgres "${DATABASE_URL}" up

app "${SERVER_TYPE}"
