apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tawny-web-web-ingressroute
  namespace: tawny
  labels:
    tawny.sh/name: tawny-web-ingressroute
    tawny.sh/component: tawny-ingressroute
    tawny.sh/part-of: tawny-core
    tawny.sh/managed-by: tawny-core
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`tawny.internal`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: tawny-web-svc
          namespace: tawny
          port: 9091
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tawny-api-web-ingressroute
  namespace: tawny
  labels:
    tawny.sh/name: tawny-web-ingressroute
    tawny.sh/component: tawny-ingressroute
    tawny.sh/part-of: tawny-core
    tawny.sh/managed-by: tawny-core
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`tawny.internal`) && PathPrefix(`/api`)
      services:
        - kind: Service
          passHostHeader: true
          name: tawny-api-svc
          namespace: tawny
          port: 9090
      middlewares:
        - name: tawny-api-stripprefix
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tawny-web-websecure-ingressroute
  namespace: tawny
  labels:
    tawny.sh/name: tawny-web-websecure-ingressroute
    tawny.sh/component: tawny-ingressroute
    tawny.sh/part-of: tawny-core
    tawny.sh/managed-by: tawny-core
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`tawny.internal`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: tawny-web-svc
          namespace: tawny
          port: 9091
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tawny-api-websecure-ingressroute
  namespace: tawny
  labels:
    tawny.sh/name: tawny-web-websecure-ingressroute
    tawny.sh/component: tawny-ingressroute
    tawny.sh/part-of: tawny-core
    tawny.sh/managed-by: tawny-core
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`tawny.internal`) && PathPrefix(`/api`)
      services:
        - kind: Service
          passHostHeader: true
          name: tawny-api-svc
          namespace: tawny
          port: 9090
      middlewares:
        - name: tawny-api-stripprefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tawny-api-stripprefix
  namespace: tawny
  labels:
    tawny.sh/name: tawny-api-stripprefix-middleware
    tawny.sh/component: tawny-middleware
    tawny.sh/part-of: tawny-core
    tawny.sh/managed-by: tawny-core
spec:
  stripPrefix:
    prefixes:
      - /api