---
apiVersion: v1
kind: Service
metadata:
  name: tawny-web-svc
  namespace: tawny
  labels:
    tawny.sh/name: tawny-web
    tawny.sh/component: tawny-web-svc
    tawny.sh/part-of: tawny-core
    tawny.sh/managed-by: tawny-core
spec:
  selector:
    tawny.sh/name: tawny-web
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tawny-api-svc
  namespace: tawny
  labels:
    tawny.sh/name: tawny-api
    tawny.sh/component: tawny-api-svc
    tawny.sh/part-of: tawny-core
    tawny.sh/managed-by: tawny-core
spec:
  selector:
    tawny.sh/name: tawny-api
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
