// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: example.sql

package store

import (
	"context"
)

const exampleSelectAll = `-- name: ExampleSelectAll :many
SELECT text, created_by, created_at, updated_at FROM examples
`

func (q *Queries) ExampleSelectAll(ctx context.Context) ([]Examples, error) {
	rows, err := q.db.Query(ctx, exampleSelectAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Examples{}
	for rows.Next() {
		var i Examples
		if err := rows.Scan(
			&i.Text,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
